FROM node:20-alpine as build
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the Vite default port
EXPOSE 5173

# Start the Vite dev server. 
# The --host flag is required to expose the server outside the Docker container.
CMD ["npm", "run", "dev", "--", "--host"]