spring.application.name=backend

spring.datasource.url=jdbc:postgresql://postgres:5432/franchiseiq
spring.datasource.username=franchise_user
spring.datasource.password=franchise_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.threads.virtual.enabled=true

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
